# spring.application.name=api

# spring.datasource.url=jdbc:postgresql://localhost:5432/migopan_db
# spring.datasource.username=postgres
# spring.datasource.password=minha_senha_secreta

# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=true

# spring.flyway.enabled=true
# # Habilita o comando de clean no Flyway e autoriza a limpeza em caso de erro de validação
# spring.flyway.clean-disabled=false
# spring.flyway.clean-on-validation-error=true


# Rodar Local -> 
spring.application.name=api

# Desativa completamente a auto-configuração do Flyway
spring.autoconfigure.exclude=org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

# Configuração do banco H2 em memória
spring.datasource.url=jdbc:h2:mem:migopan_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o Console Web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console