spring.application.name=api

# Configuração do H2 em memória
spring.datasource.url=jdbc:h2:mem:migopan_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# O Hibernate cria/atualiza as tabelas automaticamente no H2 para testes rápidos
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desativamos o Flyway aqui porque os scripts do Flyway foram feitos para PostgreSQL 
# e a sintaxe SQL pode dar conflito com o H2. O Hibernate cuida de criar as tabelas no H2.
spring.flyway.enabled=false

# Habilita a interface web do H2 no navegador (acesse: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console