spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/migopan_db
spring.datasource.username=postgres
spring.datasource.password=minha_senha_secreta

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
# Habilita o comando de clean no Flyway e autoriza a limpeza em caso de erro de validação
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true

# spring.application.name=api

# # Configuração do H2 em memória para ambiente de desenvolvimento local
# spring.datasource.url=jdbc:h2:mem:migopan_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # Desativa o Flyway para não tentar buscar o Postgres
# spring.flyway.enabled=false

# # Habilita o console web do H2
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console