spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/migopan_db
spring.datasource.username=postgres
spring.datasource.password=minha_senha_secreta

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
# Habilita o comando de clean no Flyway e autoriza a limpeza em caso de erro de validação
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true