CREATE TABLE tb_groups (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL, 
    descricao TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
